#!/bin/bash

#ensure buffer is empty
sudo ../scull_unload
sudo ../scull_load

sleep 2
./testcase1
sleep 7

sleep 2
./testcase2
sleep 7

sleep 2
./testcase3
sleep 12

sleep 2
./testcase4
sleep 12

sleep 2

sleep 2
./testcase5
sleep 7

sleep 2
./testcase6
sleep 7

sleep 2
./testcase7
sleep 12
