#!/bin/bash


echo ""
echo ""
echo "***************************"
echo "*   Running test case 4   *"
echo "*-------------------------*"
echo "* 2 Producers : 50 items  *"
echo "* 1 Consumer  : 100 items *"
echo "***************************"
./producer 50 GREY&
./producer 50 RED&
sleep 0.1
./consumer 100 &
# clear buffer
cat /dev/scullbuffer > /dev/null
