#!/bin/bash

echo ""
echo ""
echo "***************************"
echo "*   Running test case 1   *"
echo "*-------------------------*"
echo "* 1 Producer  : 50 items  *"
echo "* 1 Consumer  : 50 items  *"
echo "***************************"
./producer 50 GREEN&
sleep 0.1
./consumer 50 &
# clear buffer
cat /dev/scullbuffer > /dev/null
