#!/bin/bash

echo ""
echo ""
echo "***************************"
echo "*   Running test case 5   *"
echo "*-------------------------*"
echo "* 1 Producer  : 50 items  *"
echo "* 2 Consumers : 25 items  *"
echo "***************************"
./producer 50 RED > PRODUCER_TEST_5_RED
sleep 0.1
./consumer 25 > CONSUMER_TEST_5_1
./consumer 25 > CONSUMER_TEST_5_2
# clear buffer
cat /dev/scullbuffer > /dev/null
